[package]
name = "MusicApp"
version = "0.1.0"
edition = "2024"

[dependencies]
audiotags = "0.5.0"
eframe = "0.31.1"
egui = "0.31.1"
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rfd = "0.15.3"
youtube_dl = "0.10.0"
